### ISSUE TITLE
Why did some files lost and some files remain?

### ISSUE THREAD

**Issue by yatszhash** [fgregg/febrl#2]
I forked this project and compared it with the source for ver 4.2.0 from source forge.

I find in this github repository, there aren't some files (for example, auxiliary.py) that are in the source form source forge, and vice versa (e.g. address.py).

That causes the tests failures for the source from the github.

**Comment by fgregg** [comment]
Because there was code in the source forge tarball that was not under sourceforce version control. Added those files.

**Comment by yatszhash** [comment]
thanks. ok, I fix tests by myself in my fork.
